name: Deploy-Android

on:
  workflow_dispatch:

env:
  APP_CENTER_TOKEN: ${{ secrets.APP_CENTER_API_KEY  }}
  APP_NAME: ${{ 'Robot Inc/Robot'  }}
  UPLOAD_FILE: ${{ 'android/app/build/outputs/apk/app-release.apk'  }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: "17"

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build android
        run: cd android && ./gradlew assembleDebug

      - name: Upload to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: ${{ env.APP_NAME }}
          token: ${{ env.APP_CENTER_TOKEN }}
          group: ${{ env.TESTING_GROUP }}
          file: ${{ env.UPLOAD_FILE }}
          notifyTesters: true
          debug: false
